<!DOCTYPE html>
<html lang="fr-FR">

<head>
 <title>CGU | Cité d'Ex</title>
 <meta charset="utf-8">
 <meta name="format-detection" content="telephone=no">
 <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0,  user-scalable=0">
 <meta http-equiv="X-UA-Compatible" content="IE=Edge">
 <meta name="keywords" content="Découvrir, a propos, description">
 <meta name="date" content="Dec 26">
 <!-- Favicon Icon -->
 <link rel="icon" type="image/png" href="assets/images/favicon.png">
 <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">
 <link rel="stylesheet" type="text/css" href="venobox/venobox.css">
 <link rel="stylesheet" type="text/css" href="assets/css/plugin_theme_css.css">
 <link rel="stylesheet" type="text/css" href="style.css">
 <link rel="stylesheet" type="text/css" href="assets/css/responsive.css">
 <!-- modernizr js -->
 <script src="assets/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<body>
 <?php
 require_once "inc/header.php";
 ?>
 <!-- mobile menu -->

 <!-- End Mobile Menu -->
 <!-- breadcumb area -->
 <div class="breadcumb-area">
  <div class="container">
   <div class="row">
    <div class="col-md-12 txtc  text-center ccase">
     <div class="brpt">
      <h2>CGU</h2>
     </div>
     <div class="breadcumb-inner">
      <ul>
       <li><a href="index.php">Accueil</a></li>
       <li><i class="icofont-thin-right"></i></li>
       <li><span class="current">CGU</span></li>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>

 <div class="cgubox">

  <div>
   <div style="clear:both;">
    <p style="margin-top:0pt; margin-bottom:10pt;">&nbsp;</p>
   </div>
   <!--
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:center; line-height:115%; font-size:12pt;"><strong><span style="font-family:Arial;">CONDITIONS G&Eacute;N&Eacute;RALES D&rsquo;UTILISATION</span></strong></p>
-->
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:center; line-height:115%; font-size:12pt;"><strong><span style="font-family:Arial;">&nbsp;</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 1 &ndash; PR&Eacute;AMBULE</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Les pr&eacute;sentes conditions g&eacute;n&eacute;rales d&rsquo;utilisation (ci-apr&egrave;s les &laquo; CGU &raquo;) r&eacute;gissent les relations contractuelles entre la plateforme de l&rsquo;association CITEDEX enregistr&eacute;e au RCS de Bordeaux sous le num&eacute;ro 927 592 220 00010 et dont le si&egrave;ge social est situ&eacute; &ldquo;60 rue C. de FOUCAULD 33150 CENON et tout Visiteur et/ou Utilisateur telles que d&eacute;finies ci-apr&egrave;s.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Visiteur et/ou l&rsquo;Utilisateur d&eacute;clarent avoir lu et compris l&rsquo;int&eacute;gralit&eacute; des CGU et s&rsquo;engagent &agrave; les respecter.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:normal; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:normal;"><strong><span style="font-family:Arial;">ARTICLE 2 &ndash; D&Eacute;FINITIONS</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Les termes d&eacute;butant par une majuscule au sein des CGU, qu&rsquo;ils soient utilis&eacute;s au singulier ou au pluriel, auront la signification qui leur est donn&eacute;e ci-apr&egrave;s.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><strong><span style="font-family:Arial;">Le site&nbsp;</span></strong><span style="font-family:Arial;">: d&eacute;signe la plateforme interactive d&eacute;nomm&eacute;e &ldquo;CITEDEX enregistr&eacute;e au RCS de Bordeaux sous le num&eacute;ro 927 592 220 00010 et dont le si&egrave;ge est situ&eacute; &ldquo;60 rue C. de FOUCAULD 33150 CENON&rdquo;.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><strong><span style="font-family:Arial;">CGU</span></strong><span style="font-family:Arial;">&nbsp;: d&eacute;signe les pr&eacute;sentes Conditions G&eacute;n&eacute;rales d&rsquo;Utilisation du Site de</span><span style="font-family:Arial;">&nbsp;&nbsp;</span><span style="font-family:Arial;">s&rsquo;appliquant &agrave; l&rsquo;acc&egrave;s et &agrave; l&rsquo;utilisation du Site et de ses Services.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><strong><span style="font-family:Arial;">Donn&eacute;es &agrave; caract&egrave;re personnel&nbsp;</span></strong><span style="font-family:Arial;">: toute information se rapportant &agrave; une personne physique identifi&eacute;e ou identifiable (ci-apr&egrave;s d&eacute;nomm&eacute;e &laquo;personne concern&eacute;e&raquo;) ; est r&eacute;put&eacute;e &ecirc;tre une &laquo;personne physique identifiable&raquo; une personne physique qui peut &ecirc;tre identifi&eacute;e, directement ou indirectement, notamment par r&eacute;f&eacute;rence &agrave; un identifiant, tel qu&rsquo;un nom, un num&eacute;ro d&rsquo;identification, des donn&eacute;es de localisation, un identifiant en ligne, ou &agrave; un ou plusieurs &eacute;l&eacute;ments sp&eacute;cifiques propres &agrave; son identit&eacute; physique, physiologique, g&eacute;n&eacute;tique, psychique, &eacute;conomique, culturelle ou sociale.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><strong><span style="font-family:Arial;">Donn&eacute;es Utilisateurs</span></strong><span style="font-family:Arial;">&nbsp;: d&eacute;signe l&rsquo;ensemble des donn&eacute;es ou informations communiqu&eacute;es, saisies, ou import&eacute;es par les Utilisateurs en vue d&rsquo;&ecirc;tre trait&eacute;es dans le cadre de la Mise en relation.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><strong><span style="font-family:Arial;">&Eacute;l&eacute;ments</span></strong><span style="font-family:Arial;">: d&eacute;signe tout contenu composant le Site, en ce compris, sans que cette liste ne soit limitative, textes, photographies, images, vid&eacute;os, messages et/ou autres contenus de quelque nature qu&rsquo;il soit.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><strong><span style="font-family:Arial;">Identifiants</span></strong><span style="font-family:Arial;">&nbsp;: d&eacute;signe l&rsquo;identifiant de connexion destin&eacute; &agrave; identifier un Abonn&eacute; et le mot de passe personnel et confidentiel de l&rsquo;abonn&eacute; et lui permettant d&rsquo;acc&eacute;der &agrave; son Compte.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify;"><span style="line-height:115%; font-family:Arial; font-size:10pt;">Site : d&eacute;signe le site internet accessible &agrave; l&rsquo;adresse&nbsp;</span><a href="https://www.cazaexpert.fr" style="text-decoration:none;"><u><span style="line-height:115%; font-family:Arial; font-size:10pt; color:#1155cc;">https://www.citedex.fr</span></u></a><span style="line-height:115%; font-family:Arial; font-size:10pt;">&nbsp;&nbsp;</span><span style="line-height:115%; font-family:Arial; font-size:10pt;">sur lequel est h&eacute;berg&eacute;e la Plateforme.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:normal; font-size:10pt;"><strong><span style="font-family:Arial;">Visiteur</span></strong><span style="font-family:Arial;">&nbsp;: d&eacute;signe l&rsquo;internaute qui visite le Site, sans cr&eacute;er de compte utilisateur. En acc&eacute;dant &agrave; la Plateforme et en cr&eacute;ant un compte Utilisateur, le Visiteur.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:normal; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:normal;"><strong><span style="font-family:Arial;">ARTICLE 3 &ndash; OBJET</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:normal; font-size:10pt;"><span style="font-family:Arial;">Les CGU ont pour objet de d&eacute;finir les modalit&eacute;s et conditions d&rsquo;utilisation du Site par les Visiteurs.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 4 &ndash; HI&Eacute;RARCHIE &ndash; ACCEPTATION &ndash; MODIFICATIONS</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-indent:36pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">a. Hi&eacute;rarchie des CGU</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Service est fourni suivant les CGU et ces derni&egrave;res pr&eacute;vaudront sur toutes autres conditions figurant dans tout autre document, sauf d&eacute;rogation pr&eacute;alable, expresse et &eacute;crite.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-indent:36pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">b. Acceptation des CGU</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Les pr&eacute;sentes CGU r&eacute;gissent les relations contractuelles entre CITEDEX et le Visiteur et/ou l&rsquo;Utilisateur.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Site est d&rsquo;acc&egrave;s libre et gratuit &agrave; tout Visiteur.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">La navigation sur le Site suppose l&rsquo;acceptation par tout Visiteur des pr&eacute;sentes CGU.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">La simple connexion au Site emportera acceptation pleine et enti&egrave;re des pr&eacute;sentes CGU par le Visiteur.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">L&rsquo;acceptation des pr&eacute;sentes CGU suppose de la part du Visiteur qu&rsquo;il jouisse de la capacit&eacute; juridique n&eacute;cessaire pour cela, ou &agrave; d&eacute;faut qu&rsquo;ils en aient l&rsquo;autorisation d&rsquo;un tuteur ou d&rsquo;un curateur s&rsquo;ils sont incapables, de leur repr&eacute;sentant l&eacute;gal s&rsquo;ils sont mineurs, ou encore qu&rsquo;ils soient titulaires d&rsquo;un mandat s&rsquo;ils agissent pour le compte d&rsquo;une personne morale.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-indent:36pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">c. Modifications des CGU</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Toute modification des CGU est notifi&eacute;e &eacute;lectroniquement &agrave; l&rsquo;Utilisateur, qui est libre d&rsquo;en refuser l&rsquo;application et mettre ainsi un terme &agrave; son inscription.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">L&rsquo;invalidit&eacute; d&rsquo;une disposition des CGU n&rsquo;affecte pas la validit&eacute; des autres.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le fait que CITEDEX ne se pr&eacute;vale pas des CGU &agrave; un moment ne saurait &ecirc;tre interpr&eacute;t&eacute; comme une renonciation de s&rsquo;en pr&eacute;valoir ult&eacute;rieurement.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:10pt;"><strong><span style="font-family:Arial;">&nbsp;</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 5 &ndash; MODALIT&Eacute; FINANCI&Egrave;RE DU SERVICE</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Particulier est inform&eacute; que l&rsquo;utilisation</span><span style="font-family:Arial;">&nbsp;&nbsp;</span><span style="font-family:Arial;">du Site est gratuite.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">&nbsp;</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 6 &ndash; PROC&Eacute;DURE D&rsquo;ACC&Egrave;S &Agrave; L&apos;ABONNEMENT</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:normal; font-size:10pt;"><span style="font-family:Arial;">La cr&eacute;ation d&rsquo;un Compte Abonn&eacute; est permise &agrave; toute personne physique, majeure et capable.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">A ce titre, l&apos;utilisateur Particulier doit remplir un formulaire d&rsquo;inscription et fournir certaines donn&eacute;es. A ce titre, l&apos;utilisateur Particulier s&rsquo;engage &agrave; fournir des informations exactes, compl&egrave;tes, sinc&egrave;res et pr&eacute;cises.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">L&rsquo;Utilisateur Particulier devra renseigner notamment les informations suivantes :</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">Nom et pr&eacute;nom ;</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">Num&eacute;ro de t&eacute;l&eacute;phone ;</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">Adresse email ;</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:10pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">Mot de passe.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX peut, &agrave; des fins de pr&eacute;vention ou d&eacute;tection des fraudes, mettre en place un syst&egrave;me de v&eacute;rification de certaines des informations fournies par l&rsquo;abonn&eacute; et notamment du num&eacute;ro de t&eacute;l&eacute;phone et de l&rsquo;adresse email.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">En cas de changement de la situation telle que d&eacute;clar&eacute;e au jour de la cr&eacute;ation du Compte, l&rsquo;Utilisateur s&rsquo;engage &agrave; mettre &agrave; jour les informations le concernant.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX ne saurait &ecirc;tre tenue responsable au cas o&ugrave; elle n&rsquo;aurait pas &eacute;t&eacute; avis&eacute;e d&rsquo;un changement de situation de l&rsquo;abonn&eacute; ou d&rsquo;informations mensong&egrave;res, invalides ou erron&eacute;es le concernant.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX n&rsquo;a pas pour obligation de v&eacute;rifier la r&eacute;alit&eacute; de l&rsquo;identit&eacute; de l&apos;utilisateur Particulier et ne dispose pas des moyens techniques et/ou l&eacute;gaux le lui permettant.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">N&eacute;anmoins, en cas de doute sur la r&eacute;alit&eacute; des informations fournies ou en cas de d&eacute;nonciation par toute personne laissant pr&eacute;sumer l&rsquo;existence d&rsquo;une usurpation d&rsquo;identit&eacute; ou l&rsquo;existence d&rsquo;informations fictives, CITEDEX se r&eacute;serve le droit :</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:normal; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">&nbsp;de ne pas proc&eacute;der &agrave; la cr&eacute;ation du Compte</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:normal; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">&nbsp;de mettre hors ligne le Compte</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:10pt; text-indent:-18pt; text-align:justify; line-height:normal; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">&nbsp;de solliciter des justificatifs aupr&egrave;s du Particulier mis en cause.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">La combinaison identifiant/mot de passe est strictement personnelle. Il appartient donc &agrave; l&rsquo;Abonn&eacute; de garantir le maintien de la confidentialit&eacute; de cette combinaison lui permettant l&rsquo;acc&egrave;s au Service.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">En cas de perte et/ou d&rsquo;oubli du mot de passe, le titulaire du compte pourra demander la r&eacute;initialisation de son mot de passe &agrave; partir de la Plateforme.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">L&rsquo;Abonn&eacute; s&rsquo;engage &eacute;galement &agrave; ne communiquer ces informations d&rsquo;identification et de mot de passe &agrave; aucune autre personne, ni &agrave; les pr&ecirc;ter, donner, vendre et, de mani&egrave;re g&eacute;n&eacute;rale, mettre le Compte et/ou le mot de passe &agrave; la disposition d&rsquo;un tiers, pour quelque raison que ce soit. A d&eacute;faut la responsabilit&eacute; de CITEDEX ne pourra &ecirc;tre aucunement engag&eacute;e en cas d&rsquo;utilisation frauduleuse de ces informations.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">En cas d&rsquo;utilisation frauduleuse des identifiants de connexion de l&rsquo;Utilisateur du fait d&rsquo;une faute ou n&eacute;gligence imputable de celui-ci, ou &agrave; toute personne sous son contr&ocirc;le ou son autorit&eacute; hi&eacute;rarchique, l&rsquo;utilisateur sera responsable envers</span><span style="font-family:Arial; color:#ff0000;">&nbsp;</span><span style="font-family:Arial;">CITEDEX de toute perte ou d&eacute;t&eacute;rioration de donn&eacute;es quelles qu&rsquo;elles soient, et plus g&eacute;n&eacute;ralement de tout dommage subi en raison d&rsquo;une utilisation du service non conforme aux r&egrave;gles &eacute;dict&eacute;es dans les pr&eacute;sentes conditions g&eacute;n&eacute;rales.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-indent:36pt; text-align:justify; line-height:normal; font-size:10pt;"><span style="font-family:Arial;">b. Disponibilit&eacute; du site</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:normal; font-size:10pt;"><span style="font-family:Arial;">L&rsquo;Abonn&eacute; peut acc&eacute;der &agrave; la Plateforme 7 jours sur 7 et 24 heures sur 24 via une connexion internet. La plateforme est compatible avec les principaux navigateurs : Chrome, Firefox, Edge, Safari sur des versions r&eacute;centes.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">L&rsquo;Abonn&eacute; est inform&eacute; que la connexion au site s&rsquo;effectue via le r&eacute;seau Internet. Il a connaissance des al&eacute;as techniques qui peuvent affecter ce r&eacute;seau et entra&icirc;ner des ralentissements ou des indisponibilit&eacute;s rendant la connexion impossible. CITEDEX ne peut &ecirc;tre tenue responsable des difficult&eacute;s d&rsquo;acc&egrave;s &agrave; la Plateforme dues &agrave; des perturbations du r&eacute;seau Internet.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">De mani&egrave;re g&eacute;n&eacute;rale, CITEDEX fait ses meilleurs efforts afin de rendre le site disponible 24h/24, 7j/7 sauf cas de force majeure ou de toute panne technique &eacute;ventuelle des services d&rsquo;h&eacute;bergement, ou toute autre cause ext&eacute;rieure &agrave; CITEDEX.&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">A ce titre, CITEDEX est tenue d&rsquo;une obligation de moyens.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">L&rsquo;acc&egrave;s au Site peut &ecirc;tre momentan&eacute;ment interrompu afin d&rsquo;assurer la maintenance.. L&rsquo;acc&egrave;s au Site et/ou au Compte peuvent &eacute;galement &ecirc;tre momentan&eacute;ment interrompu en cas de n&eacute;cessit&eacute; d&rsquo;effectuer une maintenance d&rsquo;urgence, de s&eacute;curit&eacute; ou de rem&eacute;dier &agrave; une anomalie. Dans cette hypoth&egrave;se, CITEDEX pourra proc&eacute;der, sans pr&eacute;avis, &agrave; une interruption momentan&eacute;e du Site et/ou du Compte. CITEDEX s&rsquo;efforcera n&eacute;anmoins d&rsquo;en informer l&apos;utilisateur dans les meilleurs d&eacute;lais.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX ne pourra &ecirc;tre tenu responsable des cons&eacute;quences &eacute;ventuelles de cette indisponibilit&eacute;.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:10pt;"><strong><span style="font-family:Arial;">&nbsp;</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 7&ndash; RESPONSABILIT&Eacute;</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Il appartient &agrave; l&rsquo;Abonn&eacute; de prendre toutes les pr&eacute;cautions utiles &agrave; la conservation des donn&eacute;es et informations qu&rsquo;il d&eacute;pose,</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Visiteur et/ou l&rsquo;Abonn&eacute; est &eacute;galement inform&eacute; que CITEDEX ne peut ni v&eacute;rifier ni garantir la v&eacute;racit&eacute;, l&rsquo;exhaustivit&eacute; et la pr&eacute;cision des informations transmises via le Site.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX ne saurait donc &ecirc;tre tenus pour responsable des erreurs manifestes ou non et de toute information impr&eacute;cise, trompeuse ou erron&eacute;e, ou bien de tout manque d&rsquo;information quel qu&rsquo;il Toute action dirig&eacute;e contre le Visiteur par un tiers en relation ou provenant de l&rsquo;ex&eacute;cution ou de l&rsquo;inex&eacute;cution des CGU par le Visiteur n&rsquo;ouvre pas droit &agrave; r&eacute;paration.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX ne saurait non plus &ecirc;tre tenue responsable de toute difficult&eacute; r&eacute;sultant de l&rsquo;environnement informatique ou r&eacute;seau du Visiteur, des fournisseurs tiers du Visiteur et/ou Abonn&eacute; et/ou fournisseur d&rsquo;acc&egrave;s &agrave; Internet du Visiteur et/ou Abonn&eacute;.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Visiteur et/ou l&rsquo;Abonn&eacute; reconna&icirc;t et accepte que la pr&eacute;sente clause limitative de responsabilit&eacute; constitue une condition essentielle et d&eacute;terminante de l&rsquo;engagement de CITEDEX.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 8 &ndash; GARANTIE</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Dans la limite permise par la loi, CITEDEX exclut express&eacute;ment toute garantie autre que celles impos&eacute;es par la loi.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">En particulier, CITEDEX ne garantit pas que le Site est exempt d&rsquo;anomalies et que leur fonctionnement sera ininterrompu et exclut express&eacute;ment la garantie des vices cach&eacute;s telle que d&eacute;finie par les articles 1641 et suivants du Code civil.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Visiteur et/ou Abonn&eacute; d&eacute;clarent avoir une parfaite connaissance de l&rsquo;Internet et de ses limites. Le Visiteur et/ou l&rsquo;Abonn&eacute; reconnaissent notamment que les transmissions sur Internet ne sont pas s&eacute;curis&eacute;es et peuvent &ecirc;tre retard&eacute;es, perdues, intercept&eacute;es, corrompues et que la transmission d&rsquo;informations confidentielles via Internet est r&eacute;alis&eacute;e par le Visiteur et/ou Abonn&eacute; &agrave; ses risques et p&eacute;rils.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Les garanties d&eacute;finies par le pr&eacute;sent Article sont sujettes aux stipulations de l&rsquo;Article &laquo; Responsabilit&eacute; &raquo; des pr&eacute;sentes.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 9 &ndash; DONN&Eacute;ES ABONN&Eacute;S</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-indent:36pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">a. Propri&eacute;t&eacute; des donn&eacute;es de l&rsquo;Abonn&eacute;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">L&rsquo;Utilisateur reste le propri&eacute;taire exclusif des donn&eacute;es contractuelles (les &laquo; Donn&eacute;es Utilisateurs &raquo;) confi&eacute;es. A l&rsquo;exception des Donn&eacute;es Abonn&eacute;es et des Donn&eacute;es Personnelles, le Site et l&rsquo;ensemble de ses contenus sont la propri&eacute;t&eacute; exclusive de CITEDEX.&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX ne consent &agrave; chaque Abonn&eacute; qu&rsquo;un droit non-exclusif, incessible et temporaire d&rsquo;utiliser le Service.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-indent:36pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">b. Confidentialit&eacute; des donn&eacute;es de l&rsquo;Abonn&eacute;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">En utilisant le Service, l&rsquo;Abonn&eacute; confie &agrave; CITEDEX des informations. L&apos;Abonn&eacute; conserve l&rsquo;enti&egrave;re propri&eacute;t&eacute; de ces informations. CITEDEX ne revendique aucun droit de propri&eacute;t&eacute; les concernant. Les pr&eacute;sentes CGU n&rsquo;accordent aucun droit sur ces informations ou la propri&eacute;t&eacute; intellectuelle, &agrave; l&rsquo;exception des droits limit&eacute;s requis pour l&rsquo;ex&eacute;cution du Service et d&eacute;finis &agrave; l&rsquo;article 16.2.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">A ce titre, l&rsquo;Abonn&eacute; est inform&eacute; et consent que ces informations confidentielles pr&eacute;sentes dont dispose CITEDEX peuvent &ecirc;tre transmises aux autres Abonn&eacute;s pour les besoins du Service, dans le respect des r&egrave;gles de confidentialit&eacute; applicables.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 9 &ndash; DONN&Eacute;ES PERSONNELLES</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Chacune des Parties fait son affaire des obligations lui incombant au titre de la r&eacute;glementation relative &agrave; la protection des donn&eacute;es &agrave; caract&egrave;re personnel, en particulier le R&egrave;glement n&deg;2016/679 relatif &agrave; la protection des personnes physiques &agrave; l&rsquo;&eacute;gard du traitement des donn&eacute;es &agrave; caract&egrave;re personnel et &agrave; la libre circulation de ces donn&eacute;es (ci-apr&egrave;s &laquo; RGPD &raquo;) et la Loi n&deg;78-17 du 6 janvier 1978 relative &agrave; l&rsquo;informatique, aux fichiers et aux libert&eacute;s, modifi&eacute;e par la Loi n&deg; 2018-493 du 20 juin 2018.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX prend les mesures propres &agrave; assurer la protection et la confidentialit&eacute; des informations nominatives qu&rsquo;elle d&eacute;tient ou qu&rsquo;elle traite dans le respect des dispositions de la r&eacute;glementation applicable.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX recueille des informations lors de la Demande et la souscription des Services par l&rsquo;Utilisateur qui font l&rsquo;objet d&rsquo;un traitement informatique.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Dans ce cadre, CITEDEX est le responsable de traitement et a mis en &oelig;uvre une politique de protection des donn&eacute;es personnelles, consultable ici : https://www.citedex.fr/politique-de-confidentialite/</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:10pt;"><strong><span style="font-family:Arial;">&nbsp;</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 11 &ndash; PROPRI&Eacute;T&Eacute; INTELLECTUELLE</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le pr&eacute;sent site web, y compris son contenu, est prot&eacute;g&eacute; par les lois sur la propri&eacute;t&eacute; intellectuelle en vigueur, notamment en vertu de l&apos;article L.122-6 du Code de la propri&eacute;t&eacute; intellectuelle.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Il en est de m&ecirc;me pour les signes distinctifs de</span><span style="line-height:115%; font-family:Arial; font-size:9pt;">s Droits de&nbsp;</span><span style="font-family:Arial;">CITEDEX</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Visiteur et/ou l&rsquo;Abonn&eacute; reconna&icirc;t que les &eacute;l&eacute;ments, y compris de fa&ccedil;on non limitative, les textes, la base de donn&eacute;es, les programmes informatiques, musiques, sons, photos, graphiques, vid&eacute;os qui composent le Site sont prot&eacute;g&eacute;s par le droit d&rsquo;auteur, le droit des marques ou tous autres droits et lois relatifs &agrave; la propri&eacute;t&eacute; intellectuelle.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Il est notamment interdit au Visiteur et/ou &agrave; l&rsquo;Abonn&eacute; de proc&eacute;der &agrave; :</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">toute repr&eacute;sentation, diffusion ou commercialisation des &eacute;l&eacute;ments du Site, des Services, que ce soit &agrave; titre gracieux ou on&eacute;reux ;</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">toute forme d&rsquo;utilisation du Site, de la Plateforme et des Services de quelque fa&ccedil;on que ce soit aux fins de conception, r&eacute;alisation, diffusion ou commercialisation d&rsquo;un service similaire, &eacute;quivalent ou de substitution ;</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">toute mise &agrave; disposition directe ou indirecte du Site, de la Plateforme et des Services au b&eacute;n&eacute;fice d&rsquo;un tiers, notamment par location, cession ou pr&ecirc;t, m&ecirc;me &agrave; titre gratuit sauf en cas d&rsquo;accord pr&eacute;alable &eacute;crit de CITEDEX ;</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:10pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">toute utilisation pour un traitement que CITEDEX n&rsquo;aura pas autoris&eacute; pr&eacute;alablement par &eacute;crit.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Visiteur n&rsquo;est pas autoris&eacute; &agrave; reproduire et/ou repr&eacute;senter</span><span style="font-family:Arial;">&nbsp;&nbsp;</span><span style="font-family:Arial;">le Site et ses &eacute;l&eacute;ments.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">En application des articles L.342-1 et suivants du Code de la propri&eacute;t&eacute; intellectuelle, il est interdit au Visiteur et/ou &agrave; l&rsquo;Abonn&eacute; :</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">d&rsquo;extraire par transfert permanent ou temporaire la totalit&eacute; ou une partie qualitativement ou quantitativement substantielle du contenu du Site ou de la Plateforme sur un autre support, par tout moyen et sous toute forme que ce soit ;</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">de r&eacute;utiliser la totalit&eacute; ou une partie qualitativement ou quantitativement substantielle du contenu du Site par la mise &agrave; disposition du public ;</span></p>
   <p style="margin-top:0pt; margin-left:36pt; margin-bottom:10pt; text-indent:-18pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">❖</span><span style="width:10.5pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">d&rsquo;exploiter commercialement aupr&egrave;s de tiers ses droits d&rsquo;acc&egrave;s au site.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX se r&eacute;serve la possibilit&eacute; de r&eacute;silier de plein droit les CGU et d&rsquo;engager toute action en cas d&rsquo;atteinte &agrave; ses droits de propri&eacute;t&eacute; intellectuelle.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-indent:36pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">b. Contenus Utilisateurs</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">En acceptant les CGU, l&rsquo;Utilisateur conc&egrave;de &agrave; CITEDEX, une licence sur l&rsquo;ensemble des Contenus Utilisateurs, pour le monde entier et pour la dur&eacute;e l&eacute;gale de protection des droits de propri&eacute;t&eacute; intellectuelle en application des l&eacute;gislations fran&ccedil;aises et europ&eacute;ennes ainsi que des conventions internationales actuelles ou futures, y compris les prolongations qui pourraient &ecirc;tre apport&eacute;es &agrave; cette dur&eacute;e.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Afin de permettre &agrave; CITEDEX d&rsquo;assurer la bonne ex&eacute;cution des Service, l&rsquo;Utilisateur conc&egrave;de &agrave; CITEDEX</span><span style="font-family:Arial;">&nbsp;&nbsp;</span><span style="font-family:Arial;">le droit de reproduire, repr&eacute;senter, diffuser, adapter, modifier, r&eacute;aliser une &oelig;uvre d&eacute;riv&eacute;e, traduire tout ou partie des Contenus Utilisateurs par tous proc&eacute;d&eacute;s, sous quelque forme que ce soit et sur tous supports (num&eacute;rique, imprim&eacute;&hellip;) connus ou inconnus &agrave; ce jour, dans le cadre des Services ou en relation avec l&rsquo;activit&eacute; de CITEDEX, et ce &agrave; des fins publicitaires, ainsi que dans le cadre d&rsquo;une diffusion sur les r&eacute;seaux sociaux sur lesquels CITEDEX est pr&eacute;sent.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 12 &ndash; LIENS HYPERTEXTES</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Site peut faire appara&icirc;tre des publicit&eacute;s g&eacute;n&eacute;r&eacute;es par des tiers.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX n&rsquo;a aucun contr&ocirc;le sur le contenu de la publicit&eacute; visible par le Visiteur et/ou l&rsquo;Abonn&eacute;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Site peut contenir des liens vers des sites Internet administr&eacute;s par des tiers.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">CITEDEX ne peut en aucun cas exploiter ou contr&ocirc;ler les informations, produits et services pr&eacute;sent&eacute;s sur ces sites tiers. Les liens sont inclus uniquement &agrave; des fins pratiques et ne constituent aucun engagement de la part de CITEDEX. Le Visiteur et/ou l&rsquo;Abonn&eacute; assume l&rsquo;enti&egrave;re responsabilit&eacute; de l&rsquo;utilisation des liens vers des sites tiers.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 13 &ndash; COMMENTAIRES ET AUTRES CONTENUS</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le Visiteur ne peut &eacute;mettre sur le Site des notes ou commentaires sans l&rsquo;accord expresse pr&eacute;alable et &eacute;crit de CITEDEX.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le visiteur ou l&rsquo;abonn&eacute; peut &eacute;mettre sur le Site des notes, des commentaires ou tout autre contenu tant que ce contenu n&rsquo;est pas ill&eacute;gal, obsc&egrave;ne, abusif, mena&ccedil;ant, diffamatoire, contrevenant aux droits de propri&eacute;t&eacute; intellectuelle, pr&eacute;judiciable &agrave; des tiers ou illicite de toute autre mani&egrave;re que ce soit et ne consiste pas ou ne contient pas de virus informatiques, de militantisme politique, de sollicitations commerciales, de mailing de masse, de cha&icirc;nes ou toute autre forme de &laquo; spam &raquo;.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Les notes et commentaires des Particuliers sont transmis aux professionnels. En outre, les notes sont prises en compte dans la s&eacute;lection des Professionnels autoris&eacute;s &agrave; fournir des Propositions personnalis&eacute;es.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 14 &ndash; DIVERS</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le fait que l&rsquo;une quelconque des stipulations des CGU soit ou devienne ill&eacute;gale ou inapplicable n&rsquo;affectera en aucune fa&ccedil;on la validit&eacute; ou l&rsquo;applicabilit&eacute; des autres stipulations des pr&eacute;sentes.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Les Parties remplaceront par voie d&rsquo;avenant les dispositions nulles par de nouvelles dispositions juridiquement valables et aussi pr&egrave;s que possible du sens et du but envisag&eacute; aux plans juridique et &eacute;conomique.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Le fait que CITEDEX n&rsquo;exerce pas, &agrave; un moment quelconque, une pr&eacute;rogative reconnue par les CGU ne pourra en aucun cas &ecirc;tre interpr&eacute;t&eacute; comme une renonciation expresse ou tacite au droit d&rsquo;exercer ladite pr&eacute;rogative &agrave; l&rsquo;avenir.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 15 &ndash; DROIT APPLICABLE AUX CGU</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Les CGU sont soumises &agrave; la loi fran&ccedil;aise.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><strong><span style="font-family:Arial;">ARTICLE 16 &ndash; LITIGE</span></strong></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">Tout litige ou toute contestation relatif &agrave; la validit&eacute;, l&rsquo;interpr&eacute;tation ou l&rsquo;ex&eacute;cution des CGU devra &ecirc;tre prioritairement r&eacute;gl&eacute; &agrave; l&rsquo;amiable avec CITEDEX. Toute r&eacute;clamation doit &ecirc;tre adress&eacute;e par &eacute;crit &agrave; l&rsquo;adresse indiqu&eacute;e au sein des Mentions L&eacute;gales consultable &agrave; l&rsquo;adresse suivante : https://www.CITEDEX.fr/mentions-legales/.</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt; text-align:justify; line-height:115%; font-size:10pt;"><span style="font-family:Arial;">En cas de d&eacute;saccord persistant entre le professionnel et CITEDEX le litige rel&egrave;vera de la comp&eacute;tence exclusive du Tribunal mat&eacute;riellement comp&eacute;tent situ&eacute; de Bordeaux .</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <p style="margin-top:0pt; margin-bottom:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
   <div style="clear:both;">
    <p style="margin-top:0pt; margin-bottom:10pt; text-align:right;">1</p>
   </div>
  </div>


 </div>
 <?php
 require_once "inc/footer.php";
 ?>
 <!-- Include All JS -->
 <script src="assets/js/vendor/jquery-3.5.1.min.js"></script>
 <script src="assets/js/bootstrap.min.js"></script>
 <script src="assets/js/isotope.pkgd.min.js"></script>
 <script src="assets/js/owl.carousel.min.js"></script>
 <script src="assets/js/slick.min.js"></script>
 <script src="assets/js/imagesloaded.pkgd.min.js"></script>
 <script src="venobox/venobox.min.js"></script>
 <script src="assets/js/jquery.appear.js"></script>
 <script src="assets/js/jquery.knob.js"></script>
 <script src="assets/js/theme-pluginjs.js"></script>
 <script src="assets/js/jquery.meanmenu.js"></script>
 <script src="assets/js/ajax-mail.js"></script>
 <script src="assets/js/theme.js"></script>
</body>

</html>